project_id: '798140'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # Docs Markdown files
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    scheme: 'identifier'
    excluded_front_matter_elements:
      - id
  # Game client files
  - source: /translations/game-client/original.json
    translation: /translations/game-client/%two_letters_code%.json
  # Game client view files
  - source: /translations/game-client/views/en.json
    translation: /translations/game-client/views/%two_letters_code%.json
